export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <header className="w-full bg-red-500">
          <h1>Header part</h1>
        </header>
        {children}
        <footer>
          <h1>Footer part</h1>
        </footer>
      </body>
    </html>
  );
}
